from snowflake.snowpark import Session, DataFrame
from snowflake.snowpark.functions import to_date, col

def get_registros_dp(session: Session) -> DataFrame:
    """
    Genera un DataFrame de snowpark con los registros a Dominos

    Columnas:

    (Ocupadas)

    FECHA: Fecha en la que el usuario se registro

    EMAIL: Email del usuario que se registro

    (Total)

    CONTEXT_INSTANCE_ID, CONTEXT_NETWORK_CARRIER, CONTEXT_SCREEN_DENSITY, EVENT_SOURCE_SLUG,
    CONTEXT_APP_BUILD, CONTEXT_APP_NAME, CONTEXT_DEVICE_MODEL, CONTEXT_NETWORK_WIFI,
    CONTEXT_APP_VERSION, CONTEXT_NETWORK_BLUETOOTH, CONTEXT_SCREEN_HEIGHT, CONTEXT_USER_AGENT,
    EVENT, EVENT_SOURCE_ID, RECEIVED_AT, CONTEXT_IP, CONTEXT_LIBRARY_NAME, CONTEXT_TIMEZONE,
    CONTEXT_TRAITS_ANONYMOUS_ID, USER_ID, UUID_TS, EMAIL, EVENT_SOURCE_NAME, ID,
    TIMESTAMP, CONTEXT_DEVICE_ADVERTISING_ID, CONTEXT_DEVICE_ID, CONTEXT_NETWORK_CELLULAR,
    CONTEXT_OS_VERSION, CONTEXT_APP_NAMESPACE, CONTEXT_LIBRARY_VERSION, CONTEXT_LOCALE,
    SEGMENT_ID, LOGIN_METHOD, ORIGINAL_TIMESTAMP, CONTEXT_DEVICE_AD_TRACKING_ENABLED,
    CONTEXT_DEVICE_NAME, CONTEXT_OS_NAME, EVENT_TEXT, CONTEXT_DEVICE_MANUFACTURER,
    CONTEXT_DEVICE_TYPE, CONTEXT_SCREEN_WIDTH, SENT_AT, SOURCE, ORDER_COMPLETED,
    FECHA
    """
    registros = (
        session
        .table('SEGMENT_EVENTS.DOMINOS_UNIFIED.SIGNUP_SUCCESS')
        .with_column('FECHA', to_date(col('SENT_AT')))
    )

    return registros